"""empty message

Revision ID: 38ed3a4a638d
Revises: 21e7516dd96a
Create Date: 2024-08-12 15:45:05.476679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ed3a4a638d'
down_revision = '21e7516dd96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('adress', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('apartment', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('postal', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('postal')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('country')
        batch_op.drop_column('apartment')
        batch_op.drop_column('adress')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
